
#include "geometry_msgs/msg/Pose.idl" 

module CustomROSTypeDataPublisher { module msg { 
struct CustomMessage
{
	unsigned long index;
	string message;
	geometry_msgs::msg::Pose pose[1024];
};
};
};
